listen_addresses = ['[::1]:53', '127.0.0.1:53']

doh_servers = true

forwarding_rules = 'dnscrypt-forwarding-rules.txt'

block_ipv6 = true

[static]
	[static.'ea-dns.rubyfish.cn']
	stamp = 'sdns://AgUAAAAAAAAAAAASZWEtZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'
	[static.'uw-dns.rubyfish.cn']
	stamp = 'sdns://AgUAAAAAAAAAAAASdXctZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'